# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  frog-darwin-arm64 = {
    pname = "frog-darwin-arm64";
    version = "1.1.0";
    src = fetchurl {
      url = "https://github.com/wevm/frog/releases/download/frog@1.1.0/frog-darwin-arm64.gz";
      sha256 = "sha256-9QbnCokyF7VHcRpyy/S9pnZ6FcI2YBzg1gAhlcI3+pM=";
    };
  };
  gh-sub-issue-darwin-arm64 = {
    pname = "gh-sub-issue-darwin-arm64";
    version = "0.5.1";
    src = fetchurl {
      url = "https://github.com/yahsan2/gh-sub-issue/releases/download/v0.5.1/gh-sub-issue_0.5.1_darwin-arm64";
      sha256 = "sha256-UmVEz2zi7kZF0horOEfP4bZUhA/hwAuE5xrKgZHVSAc=";
    };
  };
  gwq-darwin-arm64 = {
    pname = "gwq-darwin-arm64";
    version = "v0.1.1";
    src = fetchurl {
      url = "https://github.com/d-kuro/gwq/releases/download/v0.1.1/gwq_Darwin_arm64.tar.gz";
      sha256 = "sha256-G4tYAEvOL/G4WxJG5rOxTsqJoKlYeWlu5sdc9I571/s=";
    };
  };
  playwright-cli = {
    pname = "playwright-cli";
    version = "v0.1.20";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "playwright-cli";
      rev = "v0.1.20";
      fetchSubmodules = false;
      sha256 = "sha256-MSBXygESmOlZi8qryAsUN6jb30RbysdEZRBXocrXZ14=";
    };
  };
  vite-plus-darwin-arm64 = {
    pname = "vite-plus-darwin-arm64";
    version = "0.3.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/@voidzero-dev/vite-plus-cli-darwin-arm64/-/vite-plus-cli-darwin-arm64-0.3.3.tgz";
      sha256 = "sha256-opYlp3O8j+9N5ENKZ6JPNISbPCwBWeqHqFTIhT7JR1Q=";
    };
  };
}
